/**
 *Project By: Geah Sept C. Igtanloc  & John Michael F. Rivera
 * 
 * 
 * Contact Information:
 * 
 * Igtanloc: 
 * 09164974493
 * geahseptigtanloc@gmail.com
 * 
 * Rivera:
 * 09477708658 
 * johnmichaelrivera06@gmail.com
 
 Roles: 
 * 
 * Geah Sept C. Igtanloc: 
 * Edit Button
 * Delete Row Button
 * GUI Fields for Expense Name to Day ComboBox
 * 
 * John Michael F. Rivera:
 * Table
 * Add Button
 * FilterCombo Box
 * View Total Button and Field
 * 

 
 
 **/


package finalweeklyexpensetracker;

/**
 *
 * @author johnm
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter; 
import javax.swing.RowFilter; 
import javax.swing.JOptionPane;
public class WeeklyExpenseTrackerGUI extends javax.swing.JFrame {
    
private DefaultTableModel tableModel;




    
    public WeeklyExpenseTrackerGUI() {
        initComponents();
        
        
        
        tableModel = (DefaultTableModel) expenseTable.getModel(); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        expenseNameField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();
        addExpenseButton = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel6 = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewTotalButton = new javax.swing.JButton();
        totalDisplayField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Weekly Expense Tracker");

        expenseNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseNameFieldActionPerformed(evt);
            }
        });

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Expense Name");

        jLabel3.setText("Amount");

        jLabel4.setText("Category");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Transport", "Entertainment", "Other" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Day");

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        expenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense Name", "Amount", "Category", "Day"
            }
        ));
        jScrollPane1.setViewportView(expenseTable);

        addExpenseButton.setText("Add Expense");
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Filter by Day:");

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Whole Week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        filterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboBoxActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Row");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewTotalButton.setText("View Total");
        viewTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTotalButtonActionPerformed(evt);
            }
        });

        totalDisplayField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addGap(24, 24, 24)
                            .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(deleteButton)
                                    .addGap(52, 52, 52)
                                    .addComponent(addExpenseButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(viewTotalButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(totalDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expenseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExpenseButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTotalButton)
                    .addComponent(totalDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenseNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseNameFieldActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
// Get input 
String expenseName = expenseNameField.getText();
String amount = amountField.getText();
String category = categoryComboBox.getSelectedItem().toString();
String day = dayComboBox.getSelectedItem().toString();

// Add table
DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
model.addRow(new Object[]{expenseName, amount, category, day});

// Clear fields
expenseNameField.setText("");
amountField.setText("");
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void filterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboBoxActionPerformed
 // Get the selected day or "Whole Week" from the filter dropdown
    String selectedFilter = filterComboBox.getSelectedItem().toString();

    // Set up a table sorter
    DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    expenseTable.setRowSorter(sorter);

    if (selectedFilter.equals("Whole Week")) {
        // Show all rows (Monday to Sunday)
        sorter.setRowFilter(null); // No filter, show all rows

        // Call the method to calculate the total amount for the whole week
        viewTotalButtonActionPerformed(evt); // This will update the total for the whole week
    } else if (!selectedFilter.equals("All")) {
        // Filter by specific day (Monday-Sunday)
        sorter.setRowFilter(RowFilter.regexFilter(selectedFilter));
    } else {
        // Show all rows (if all is selected)
        sorter.setRowFilter(null);
    }

    }//GEN-LAST:event_filterComboBoxActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
int selectedRow = expenseTable.getSelectedRow();
        if (selectedRow != -1) {
            // Get selected row values and set them into input fields
            expenseNameField.setText(tableModel.getValueAt(selectedRow, 0).toString());
            amountField.setText(tableModel.getValueAt(selectedRow, 1).toString());
            categoryComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 2).toString());
            dayComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 3).toString());

            // Remove the old row
            tableModel.removeRow(selectedRow);

            // Add the updated row back to the table
            tableModel.addRow(new Object[]{
                expenseNameField.getText(),
                amountField.getText(),
                categoryComboBox.getSelectedItem(),
                dayComboBox.getSelectedItem()
            });

            // No need to call updateTotalSpending here anymore
        }

    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
 int selectedRow = expenseTable.getSelectedRow();
        if (selectedRow != -1) {
            // Ask for confirmation before deleting
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Are you sure you want to delete this expense?",
                    "Delete Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Remove the selected row from the table
                tableModel.removeRow(selectedRow);

                // No need to call updateTotalSpending here either
            }
        }
    

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTotalButtonActionPerformed
  double total = 0;
    
    // Get the selected filter
    String selectedFilter = filterComboBox.getSelectedItem().toString();
    
    // Get the model and create a TableRowSorter
    DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    expenseTable.setRowSorter(sorter);
    
    // Apply filter based on selected filter
    if (selectedFilter.equals("Whole Week")) {
        // No filter, show all rows
        sorter.setRowFilter(null);
    } else {
        // Filter by the selected day (e.g., Monday, Tuesday)
        sorter.setRowFilter(RowFilter.regexFilter(selectedFilter));
    }
    
    // Loop through only the visible rows (after sorting/filtering)
    int rowCount = sorter.getViewRowCount();
    for (int i = 0; i < rowCount; i++) {
        // Get the model row index of the filtered row
        int modelRow = sorter.convertRowIndexToModel(i);
        
        try {
            // Get the amount in the second column (index 1) of the model
            double amount = Double.parseDouble(model.getValueAt(modelRow, 1).toString());
            total += amount;
        } catch (NumberFormatException e) {
            // Skip this row if the amount is not a valid number
            continue;
        }
    }
    
    // Update the total field to show the calculated total
    totalDisplayField.setText(String.format("%.2f", total));
    }//GEN-LAST:event_viewTotalButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeeklyExpenseTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeeklyExpenseTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeeklyExpenseTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeeklyExpenseTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeeklyExpenseTrackerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JTextField amountField;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JComboBox dayComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField expenseNameField;
    private javax.swing.JTable expenseTable;
    private javax.swing.JComboBox filterComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totalDisplayField;
    private javax.swing.JButton viewTotalButton;
    // End of variables declaration//GEN-END:variables
}
